/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionMissionRouteImport } from './routes/vision-mission'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as CareerNavigatorRouteImport } from './routes/career-navigator'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'

const VisionMissionRoute = VisionMissionRouteImport.update({
  id: '/vision-mission',
  path: '/vision-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerNavigatorRoute = CareerNavigatorRouteImport.update({
  id: '/career-navigator',
  path: '/career-navigator',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProgramsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career-navigator': typeof CareerNavigatorRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/scholarships': typeof ScholarshipsRoute
  '/vision-mission': typeof VisionMissionRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career-navigator': typeof CareerNavigatorRoute
  '/scholarships': typeof ScholarshipsRoute
  '/vision-mission': typeof VisionMissionRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/programs': typeof ProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career-navigator': typeof CareerNavigatorRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/scholarships': typeof ScholarshipsRoute
  '/vision-mission': typeof VisionMissionRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/career-navigator'
    | '/programs'
    | '/scholarships'
    | '/vision-mission'
    | '/programs/$slug'
    | '/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/career-navigator'
    | '/scholarships'
    | '/vision-mission'
    | '/programs/$slug'
    | '/programs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/career-navigator'
    | '/programs'
    | '/scholarships'
    | '/vision-mission'
    | '/programs/$slug'
    | '/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareerNavigatorRoute: typeof CareerNavigatorRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  ScholarshipsRoute: typeof ScholarshipsRoute
  VisionMissionRoute: typeof VisionMissionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vision-mission': {
      id: '/vision-mission'
      path: '/vision-mission'
      fullPath: '/vision-mission'
      preLoaderRoute: typeof VisionMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-navigator': {
      id: '/career-navigator'
      path: '/career-navigator'
      fullPath: '/career-navigator'
      preLoaderRoute: typeof CareerNavigatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof ProgramsRoute
    }
  }
}

interface ProgramsRouteChildren {
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsSlugRoute: ProgramsSlugRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareerNavigatorRoute: CareerNavigatorRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  ScholarshipsRoute: ScholarshipsRoute,
  VisionMissionRoute: VisionMissionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
